export const queryKeys = {
  session: ['session'] as const,
  settings: ['settings'] as const,
  clients: ['clients'] as const,
  client: (id: string) => ['clients', id] as const,
  measurements: (clientId: string) => ['measurements', clientId] as const,
  measurementsList: (clientId: string) => ['measurements', clientId, 'list'] as const,
  measurementLatest: (clientId: string) => ['measurements', clientId, 'latest'] as const,
  foods: ['foods'] as const,
  food: (id: string) => ['foods', id] as const,
  exercises: ['exercises'] as const,
  exercise: (id: string) => ['exercises', id] as const,
  plans: (clientId?: string) => (clientId ? ['plans', clientId] as const : ['plans'] as const),
  plan: (id: string) => ['plans', 'detail', id] as const,
  revisions: (planId: string) => ['revisions', planId] as const,
  templates: ['templates'] as const,
  template: (id: string) => ['templates', id] as const,
  reports: ['reports'] as const,
  dashboard: ['dashboard'] as const,
  search: (query: string) => ['search', query] as const,
}
